// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/schedule/Kanban.tsx": () => import("../components/mockups/schedule/Kanban.tsx"),
  "./components/mockups/schedule/TimeGrid.tsx": () => import("../components/mockups/schedule/TimeGrid.tsx")
};
